# Generated by Django 4.0 on 2022-02-10 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='finishdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
