# Generated by Django 4.0 on 2022-02-12 18:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_done_alter_order_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
