# Generated by Django 4.0 on 2022-02-12 19:26

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='finishdate',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
