# Generated by Django 4.0 on 2022-02-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_date_alter_order_finishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daynumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='history',
            field=models.BooleanField(default=False),
        ),
    ]
