# Generated by Django 4.0 on 2022-02-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_daynumber_order_des_order_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='history',
            new_name='paid',
        ),
    ]
