# Generated by Django 4.0 on 2022-02-24 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_rename_history_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='perworker',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
